services:
  - type: web
    name: spring-boot-server
    env: java
    plan: free
    buildCommand: ./render-build.sh
    startCommand: ./start.sh
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
