services:
  - type: web
    name: spring-boot-server
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/server-1.0-SNAPSHOT.jar --spring.profiles.active=prod
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
