spring:
  datasource:
    url: jdbc:sqlite:${DATA_DIR:/data}/database.db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        # 确保在启动时创建表结构
        hbm2ddl.auto: update
      javax:
        persistence:
          schema-generation:
            database:
              action: create

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.example.server: INFO
  file:
    name: ${DATA_DIR:/data}/application.log
