spring:
  datasource:
    url: jdbc:sqlite:/data/database.db
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    com.example.server: INFO
  file:
    name: /data/application.log
